server:
  port: 9003
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest

eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    #在状态栏可见ip
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false  
name: wd
