server:
  port: 8007
spring:
  application:
    name: order-consumer
  # 使用消息队列将zipkin和sleuth的访问记录存入mysql中
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# 将当前模块的访问记录录入zipkin和sleuth中
#  zipkin:
#    base-url: http://localhost:7004
#  sleuth:
#    sampler:
#      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    prefer-ip-address: true #显示ip地址
feign:
  hystrix:
    enabled: true
name: pig
